repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-added-large-files
        args:
          - "--maxkb=20"
      - id: check-case-conflict
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: tflint
        args:
          - "--module"
          - "--config=.config/tflint.hcl"
      - id: terraform-validate
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.64.0
    hooks:
      - id: terraform_docs
      - id: terraform_fmt
        args:
          - "--args=-recursive"
  - repo: local
    hooks:
      - id: prettier1
        name: prettier1
        description: 'Format files with prettier'
        entry: prettier --write --ignore-unknown
        language: node
        'types': [ text ]
        args: [ ]
        require_serial: false
        additional_dependencies: [ "prettier@3.4.2" ]
        minimum_pre_commit_version: '0'
