---
name: Build & Push Docker Image

# Only builds the image if a release was created.
# This guarantees the commit is tagged and on main branch.
# (see https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases)

# yamllint disable-line rule:truthy
on:
  # don't run this workflow initially. we have an init-branch to fix that
  workflow_dispatch:

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/docker_dockerhub_release_callable.yml@733afe1105fc85fafc25cddbc3c34b48c2c3d6fa
    secrets: inherit
    with:
      # TODO insert correct value for image-name
      # type: string
      # required: true
      # description: Name of the image. Usually it is sensible to set this to the repository name
      image-name: "my-special-value"
      # TODO insert correct value for push
      # type: boolean
      # required: false
      # description: Flag to enable the workflow to actually push the built image to the registry
      push: "my-special-value"
      # TODO insert correct value for upload-security-scan-results
      # type: boolean
      # required: false
      # description: Upload results of trivy scan of docker image to Github Security page
      upload-security-scan-results: "my-special-value"
