---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/release.yml@6f2cce3f474216dd3b5ee5b820eb8ef6acfcfbe7 # 1.15.4
    secrets: inherit
