---
name: Prepare Release PR

# yamllint disable-line rule:truthy
on:
  # we don't want to trigger a release here as some setup is needed (done in init-workflow branch)
  workflow_dispatch:

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/terraform_module_release_manual_callable.yml@e08f390d968322fd66ff5ee4ea826015e23f04c6
    secrets: inherit
