---
name: Prepare Release PR

# yamllint disable-line rule:truthy
on:
  # we don't want to trigger a release here as some setup is needed (done in init-workflow branch)
  workflow_dispatch:

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/release_manual.yml@e8c1c3deb93315b82c4bcd4957b215fd5f94e1c2 # 1.6.3
    secrets: inherit
