---
name: Prepare Release PR

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/terraform_module_release_manual_callable.yml@514cf33cb1a4e0581c00383c2b67cabf5f76f24e
    secrets: inherit
