---
name: "Check spelling"

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_spelling_callable.yml@733afe1105fc85fafc25cddbc3c34b48c2c3d6fa
    secrets: inherit
