---
name: TfSec

# yamllint disable-line rule:truthy
on:
  pull_request:
  schedule:
    - cron: "47 3 * * 1"

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/terraform_module_terraform_tfsec_callable.yml@a28fa2f991164959262587011188af99a7f0cb20
    secrets: inherit
