---
name: Terraform

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/terraform_module_terraform_callable.yml@cd3a64ec81f3d114a2d7eebcb6b0efd1decb1af6
    secrets: inherit
