---
name: TfSec

# yamllint disable-line rule:truthy
on:
  pull_request:
  # runs mondays at 3:47 UTC refreshing the vulnerabilities
  schedule:
    - cron: "47 3 * * 1"

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/terraform_tfsec.yml@9f97dc63e5b885a7b3c57711b851a9f6c4462f7f # 1.13.0
    secrets: inherit
