---
name: TfSec

# yamllint disable-line rule:truthy
on:
  pull_request:
  # runs mondays at 3:47 UTC refreshing the vulnerabilities
  schedule:
    - cron: "47 3 * * 1"

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/terraform_module_terraform_tfsec_callable.yml@e08f390d968322fd66ff5ee4ea826015e23f04c6
    secrets: inherit
