---
name: Terraform

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/terraform_module_terraform_callable.yml@8ba51cf2e5eb1246afaa4a736ca1bb470b7039e3
    secrets: inherit
