---
name: Terraform

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/terraform_module_terraform_callable.yml@1a73d7cd5eb4439fdd6ee485fb80d03a17c1fe4b
    secrets: inherit
