---
name: TfSec

# yamllint disable-line rule:truthy
on:
  pull_request:
  # runs mondays at 3:47 UTC refreshing the vulnerabilities
  schedule:
    - cron: "47 3 * * 1"

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/terraform_tfsec.yml@c2e27d976e1221942c2186e512183ab79c1c8bac # 1.15.4
    secrets: inherit
