---
name: Terraform

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/terraform_module_terraform_callable.yml@b8306b5844712e1108311f3de60a3ac79534b572
    secrets: inherit
